spring:
  datasource:
    druid:
      url: jdbc:mysql://47.113.188.205:3306/fresh?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8
      username: fresh
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
#  data:
#    redis:
#      port: 6379
#      host: 47.99.43.189
#      password: 123123